 export const LIST_TRANSACTIONS = "LIST_TRANSACTIONS";
 export const SUMMARIZE_TRANSACTIONS = "SUMMARIZE_TRANSACTIONS";
 export const FILTER_SUMMARIZED_TRANSACTIONS = "FILTER_SUMMARIZED_TRANSACTIONS";
 export const SLICE_FILTERED_TRANSACTIONS = "SLICE_FILTERED_TRANSACTIONS";